# include <stdio.h>
# include <string.h>
# include <stdlib.h>
# include <stdbool.h>
# include "the_apple.h"

char* apple = "                     a\n"
              "                    ppl\n"
              "                  eappl\n"
              "                 eapple\n"
              "                 apple\n"
              "                 appl\n"
              "         eappleappleappleappl\n"
              "    eappleappleappleappleapple\n"
              "   appleappleappleappleappleapple\n"
              "  appleappleappleappleappleappleappl\n"
              " eappleappleappleappleappleappleapple\n"
              "appleappleappleappleappleappleappleapp\n"
              "leappleappleappleappleappleappleapplea\n"
              "ppleappleappleappleappleappleappleappl\n"
              "eappleappleappleappleappleappleappleap\n"
              "pleappleappleappleappleappleappleapple\n"
              "appleappleappleappleappleappleappleapp\n"
              "leappleappleappleapplewormmmmmmmmmmmmm\n"
              " mmmmappleappleappleappleappleappleap\n"
              "  pleappleappleappleappleappleapplea\n"
              "   ppleappleappleappleappleappleapp\n"
              "   leappleappleappleappleappleap\n"
              "     pleappleappleappleappleapp\n"
              "       leappleappleappleapple\n"
              "         appleappleappleapp\n";


char* apple2 = "                     a\n"
               "                    ppl\n"
               "                  eappl\n"
               "                 eapple\n"
               "                 apple\n"
               "                 appl\n"
               "         eappleappleappleappl\n"
               "    eappleappleappleappleapple\n"
               "   appleappleappleappleappleapple\n"
               "  appleappleappleappleappleappleappl\n"
               " eappleappleappleappleappleappleapple\n"
               "appleappleappleappleappleappleappleapp\n"
               "leappleappleappleappleappleappleapplea\n"
               "ppleappleappleappleappleappleappleappl\n"
               "eappleappleappleappleappleappleappleap\n"
               "pleappleappleappleappleappleappleapple\n"
               "appleappleappleappleappleappleappleapp\n"
               "  pleappleappleappleappleappleapplea\n"
               "   ppleappleappleappleappleappleapp\n"
               "   leappleappleappleappleappleap\n"
               "     pleappleappleappleappleapp\n"
               "       leappleappleappleapple\n"
               "         appleappleappleapp\n";
